package com.creditsafe.globaldata.operations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-09-14T16:40:48.236+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.creditsafe.com/globaldata/operations", name = "GlobalDataService")
@XmlSeeAlso({ObjectFactory.class, com.creditsafe.globaldata.datatypes.ObjectFactory.class, com.creditsafe.globaldata.datatypes.reports.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, systemtypes.ObjectFactory.class, com.creditsafe.globaldata.datatypes.administration.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.creditsafe.ObjectFactory.class})
public interface GlobalDataService {

    @WebMethod(operationName = "ImportCompaniesToPortfolio", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ImportCompaniesToPortfolio")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ImportCompaniesToPortfolio", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ImportCompaniesToPortfolioResponse")
    @RequestWrapper(localName = "ImportCompaniesToPortfolio", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ImportCompaniesToPortfolio")
    @ResponseWrapper(localName = "ImportCompaniesToPortfolioResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ImportCompaniesToPortfolioResponse")
    @WebResult(name = "ImportCompaniesToPortfolioResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.PortfolioCompanyAdditionResult importCompaniesToPortfolio(
            @WebParam(name = "portfolioId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long portfolioId,
            @WebParam(name = "fileFormat", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.FileFormat fileFormat,
            @WebParam(name = "importFile", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    byte[] importFile
    );

    @WebMethod(operationName = "FindCompanies", action = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/FindCompanies")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/FindCompanies", output = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/FindCompaniesResponse")
    @RequestWrapper(localName = "FindCompanies", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.FindCompanies")
    @ResponseWrapper(localName = "FindCompaniesResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.FindCompaniesResponse")
    @WebResult(name = "FindCompaniesResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.CompaniesList findCompanies(
            @WebParam(name = "countries", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    org.datacontract.schemas._2004._07.creditsafe.ArrayOfCountryCode countries,
            @WebParam(name = "searchCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.SearchCriteria searchCriteria,
            @WebParam(name = "customData", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CustomData customData,
            @WebParam(name = "chargeReference", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String chargeReference
    );

    @WebMethod(operationName = "GetPortfolios", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfolios")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfolios", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfoliosResponse")
    @RequestWrapper(localName = "GetPortfolios", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPortfolios")
    @ResponseWrapper(localName = "GetPortfoliosResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPortfoliosResponse")
    @WebResult(name = "GetPortfoliosResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.PortfoliosList getPortfolios(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "changedSince", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    javax.xml.datatype.XMLGregorianCalendar changedSince
    );

    @WebMethod(operationName = "GetMonitoringRules", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetMonitoringRules")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetMonitoringRules", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetMonitoringRulesResponse")
    @RequestWrapper(localName = "GetMonitoringRules", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetMonitoringRules")
    @ResponseWrapper(localName = "GetMonitoringRulesResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetMonitoringRulesResponse")
    @WebResult(name = "GetMonitoringRulesResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.CurrentPortfolioMonitoringRules getMonitoringRules(
            @WebParam(name = "portfolioId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long portfolioId
    );

    @WebMethod(operationName = "GetPortfolioSettings", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfolioSettings")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfolioSettings", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetPortfolioSettingsResponse")
    @RequestWrapper(localName = "GetPortfolioSettings", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPortfolioSettings")
    @ResponseWrapper(localName = "GetPortfolioSettingsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPortfolioSettingsResponse")
    @WebResult(name = "GetPortfolioSettingsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.CurrentPortfolioSettings getPortfolioSettings(
            @WebParam(name = "portfolioId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long portfolioId
    );

    @WebMethod(operationName = "RemoveCompaniesFromPortfolios", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemoveCompaniesFromPortfolios")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemoveCompaniesFromPortfolios", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemoveCompaniesFromPortfoliosResponse")
    @RequestWrapper(localName = "RemoveCompaniesFromPortfolios", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemoveCompaniesFromPortfolios")
    @ResponseWrapper(localName = "RemoveCompaniesFromPortfoliosResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemoveCompaniesFromPortfoliosResponse")
    @WebResult(name = "RemoveCompaniesFromPortfoliosResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.PortfolioCompanyRemovalResult removeCompaniesFromPortfolios(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "companyIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring companyIds
    );

    @WebMethod(operationName = "GetReportCustomDataSchema", action = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetReportCustomDataSchema")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetReportCustomDataSchema", output = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetReportCustomDataSchemaResponse")
    @RequestWrapper(localName = "GetReportCustomDataSchema", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportCustomDataSchema")
    @ResponseWrapper(localName = "GetReportCustomDataSchemaResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportCustomDataSchemaResponse")
    @WebResult(name = "GetReportCustomDataSchemaResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.CustomDataSchema getReportCustomDataSchema(
            @WebParam(name = "country", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CountryCode country
    );

    @WebMethod(operationName = "GetPossibleSearchCriteria", action = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetPossibleSearchCriteria")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetPossibleSearchCriteria", output = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetPossibleSearchCriteriaResponse")
    @RequestWrapper(localName = "GetPossibleSearchCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPossibleSearchCriteria")
    @ResponseWrapper(localName = "GetPossibleSearchCriteriaResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetPossibleSearchCriteriaResponse")
    @WebResult(name = "GetPossibleSearchCriteriaResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SearchCriteriaSchemaSet getPossibleSearchCriteria(
            @WebParam(name = "countries", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    org.datacontract.schemas._2004._07.creditsafe.ArrayOfCountryCode countries
    );

    @WebMethod(operationName = "TryRetrieveCompanyOnlineReport", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/TryRetrieveCompanyOnlineReport")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/TryRetrieveCompanyOnlineReport", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/TryRetrieveCompanyOnlineReportResponse")
    @RequestWrapper(localName = "TryRetrieveCompanyOnlineReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.TryRetrieveCompanyOnlineReport")
    @ResponseWrapper(localName = "TryRetrieveCompanyOnlineReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.TryRetrieveCompanyOnlineReportResponse")
    @WebResult(name = "TryRetrieveCompanyOnlineReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.reports.CompanyReportSet tryRetrieveCompanyOnlineReport(
            @WebParam(name = "country", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CountryCode country,
            @WebParam(name = "searchCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.SearchCriteria searchCriteria,
            @WebParam(name = "reportType", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CompanyReportType reportType,
            @WebParam(name = "language", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.Language language,
            @WebParam(name = "customData", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CustomData customData,
            @WebParam(name = "chargeReference", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String chargeReference,
            @WebParam(name = "storeInReportbox", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Boolean storeInReportbox,
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds
    );

    @WebMethod(operationName = "AddCompaniesToPortfolios", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/AddCompaniesToPortfolios")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/AddCompaniesToPortfolios", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/AddCompaniesToPortfoliosResponse")
    @RequestWrapper(localName = "AddCompaniesToPortfolios", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.AddCompaniesToPortfolios")
    @ResponseWrapper(localName = "AddCompaniesToPortfoliosResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.AddCompaniesToPortfoliosResponse")
    @WebResult(name = "AddCompaniesToPortfoliosResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.PortfolioCompanyAdditionResult addCompaniesToPortfolios(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "companies", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CompanyReferences companies
    );

    @WebMethod(operationName = "OrderCompanyOfflineReport", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/OrderCompanyOfflineReport")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/OrderCompanyOfflineReport", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/OrderCompanyOfflineReportResponse")
    @RequestWrapper(localName = "OrderCompanyOfflineReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.OrderCompanyOfflineReport")
    @ResponseWrapper(localName = "OrderCompanyOfflineReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.OrderCompanyOfflineReportResponse")
    @WebResult(name = "OrderCompanyOfflineReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.ReportOrder orderCompanyOfflineReport(
            @WebParam(name = "country", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CountryCode country,
            @WebParam(name = "searchCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.SearchCriteria searchCriteria,
            @WebParam(name = "reportType", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CompanyReportType reportType,
            @WebParam(name = "language", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.Language language,
            @WebParam(name = "customData", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CustomData customData,
            @WebParam(name = "chargeReference", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String chargeReference
    );

    @WebMethod(operationName = "GetCountries", action = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetCountries")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetCountries", output = "http://www.creditsafe.com/globaldata/operations/DataBrowsingService/GetCountriesResponse")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetCountriesResponse")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.CountriesList getCountries(
            @WebParam(name = "filter", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CountriesListingFilter filter
    );

    @WebMethod(operationName = "RemoveReportboxReports", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RemoveReportboxReports")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RemoveReportboxReports", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RemoveReportboxReportsResponse")
    @RequestWrapper(localName = "RemoveReportboxReports", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemoveReportboxReports")
    @ResponseWrapper(localName = "RemoveReportboxReportsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemoveReportboxReportsResponse")
    @WebResult(name = "RemoveReportboxReportsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult removeReportboxReports(
            @WebParam(name = "ids", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt ids
    );

    @WebMethod(operationName = "RetrieveCompanyOnlineReport", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RetrieveCompanyOnlineReport")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RetrieveCompanyOnlineReport", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/RetrieveCompanyOnlineReportResponse")
    @RequestWrapper(localName = "RetrieveCompanyOnlineReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RetrieveCompanyOnlineReport")
    @ResponseWrapper(localName = "RetrieveCompanyOnlineReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RetrieveCompanyOnlineReportResponse")
    @WebResult(name = "RetrieveCompanyOnlineReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.reports.CompanyReportSet retrieveCompanyOnlineReport(
            @WebParam(name = "companyId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String companyId,
            @WebParam(name = "reportType", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CompanyReportType reportType,
            @WebParam(name = "language", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.Language language,
            @WebParam(name = "customData", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CustomData customData,
            @WebParam(name = "chargeReference", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String chargeReference,
            @WebParam(name = "storeInReportbox", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Boolean storeInReportbox,
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "monitoringReference", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    String monitoringReference
    );

    @WebMethod(operationName = "ChangeCompaniesReferenceStrings", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ChangeCompaniesReferenceStrings")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ChangeCompaniesReferenceStrings", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ChangeCompaniesReferenceStringsResponse")
    @RequestWrapper(localName = "ChangeCompaniesReferenceStrings", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ChangeCompaniesReferenceStrings")
    @ResponseWrapper(localName = "ChangeCompaniesReferenceStringsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ChangeCompaniesReferenceStringsResponse")
    @WebResult(name = "ChangeCompaniesReferenceStringsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult changeCompaniesReferenceStrings(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "companies", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CompanyReferences companies
    );

    @WebMethod(operationName = "GetReportboxReports", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxReports")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxReports", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxReportsResponse")
    @RequestWrapper(localName = "GetReportboxReports", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportboxReports")
    @ResponseWrapper(localName = "GetReportboxReportsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportboxReportsResponse")
    @WebResult(name = "GetReportboxReportsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.reports.CompanyReportSet getReportboxReports(
            @WebParam(name = "ids", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt ids
    );

    @WebMethod(operationName = "CreatePortfolio", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/CreatePortfolio")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/CreatePortfolio", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/CreatePortfolioResponse")
    @RequestWrapper(localName = "CreatePortfolio", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.CreatePortfolio")
    @ResponseWrapper(localName = "CreatePortfolioResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.CreatePortfolioResponse")
    @WebResult(name = "CreatePortfolioResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.PortfoliosList createPortfolio(
            @WebParam(name = "settings", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.PortfolioSettings settings
    );

    @WebMethod(operationName = "RemovePortfolios", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemovePortfolios")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemovePortfolios", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/RemovePortfoliosResponse")
    @RequestWrapper(localName = "RemovePortfolios", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemovePortfolios")
    @ResponseWrapper(localName = "RemovePortfoliosResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.RemovePortfoliosResponse")
    @WebResult(name = "RemovePortfoliosResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult removePortfolios(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds
    );

    @WebMethod(operationName = "GetReportboxContents", action = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxContents")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxContents", output = "http://www.creditsafe.com/globaldata/operations/CompanyDataAccessService/GetReportboxContentsResponse")
    @RequestWrapper(localName = "GetReportboxContents", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportboxContents")
    @ResponseWrapper(localName = "GetReportboxContentsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetReportboxContentsResponse")
    @WebResult(name = "GetReportboxContentsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.ReportboxContents getReportboxContents(
            @WebParam(name = "filter", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.ReportboxListingFilter filter
    );

    @WebMethod(operationName = "SetDefaultChangesCheckPeriod", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetDefaultChangesCheckPeriod")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetDefaultChangesCheckPeriod", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetDefaultChangesCheckPeriodResponse")
    @RequestWrapper(localName = "SetDefaultChangesCheckPeriod", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetDefaultChangesCheckPeriod")
    @ResponseWrapper(localName = "SetDefaultChangesCheckPeriodResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetDefaultChangesCheckPeriodResponse")
    @WebResult(name = "SetDefaultChangesCheckPeriodResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult setDefaultChangesCheckPeriod(
            @WebParam(name = "days", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long days
    );

    @WebMethod(operationName = "SetMonitoringRules", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetMonitoringRules")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetMonitoringRules", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetMonitoringRulesResponse")
    @RequestWrapper(localName = "SetMonitoringRules", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetMonitoringRules")
    @ResponseWrapper(localName = "SetMonitoringRulesResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetMonitoringRulesResponse")
    @WebResult(name = "SetMonitoringRulesResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult setMonitoringRules(
            @WebParam(name = "portfolioId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long portfolioId,
            @WebParam(name = "newRules", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.MonitoringRules newRules
    );

    @WebMethod(operationName = "GetSupportedChangeEvents", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetSupportedChangeEvents")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetSupportedChangeEvents", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/GetSupportedChangeEventsResponse")
    @RequestWrapper(localName = "GetSupportedChangeEvents", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetSupportedChangeEvents")
    @ResponseWrapper(localName = "GetSupportedChangeEventsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.GetSupportedChangeEventsResponse")
    @WebResult(name = "GetSupportedChangeEventsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SupportedChangeEventsList getSupportedChangeEvents(
            @WebParam(name = "country", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.CountryCode country,
            @WebParam(name = "language", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.Language language
    );

    @WebMethod(operationName = "SetPortfolioSettings", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetPortfolioSettings")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetPortfolioSettings", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/SetPortfolioSettingsResponse")
    @RequestWrapper(localName = "SetPortfolioSettings", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetPortfolioSettings")
    @ResponseWrapper(localName = "SetPortfolioSettingsResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.SetPortfolioSettingsResponse")
    @WebResult(name = "SetPortfolioSettingsResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.SimpleResult setPortfolioSettings(
            @WebParam(name = "portfolioId", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long portfolioId,
            @WebParam(name = "newSettings", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.creditsafe.globaldata.datatypes.PortfolioSettings newSettings
    );

    @WebMethod(operationName = "ListMonitoredCompanies", action = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ListMonitoredCompanies")
    @Action(input = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ListMonitoredCompanies", output = "http://www.creditsafe.com/globaldata/operations/CompanyMonitoringService/ListMonitoredCompaniesResponse")
    @RequestWrapper(localName = "ListMonitoredCompanies", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ListMonitoredCompanies")
    @ResponseWrapper(localName = "ListMonitoredCompaniesResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations", className = "com.creditsafe.globaldata.operations.ListMonitoredCompaniesResponse")
    @WebResult(name = "ListMonitoredCompaniesResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
    public com.creditsafe.globaldata.datatypes.MonitoredCompaniesList listMonitoredCompanies(
            @WebParam(name = "portfolioIds", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt portfolioIds,
            @WebParam(name = "changedOnly", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Boolean changedOnly,
            @WebParam(name = "changedSince", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    javax.xml.datatype.XMLGregorianCalendar changedSince,
            @WebParam(name = "firstPosition", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long firstPosition,
            @WebParam(name = "pageSize", targetNamespace = "http://www.creditsafe.com/globaldata/operations")
                    Long pageSize
    );
}
