package com.mika.credit.common.enums;

import java.util.Objects;

/**
 * 国家映射
 * iso-3166标准中
 *
 * @author zj001
 */
public enum EnumCountry {
    AD("AD","Andorra","安道尔"),
    AE("AE","United Arab Emirates","阿联酋"),
    AF("AF","Afghanistan","阿富汗"),
    AG("AG","Antigua & Barbuda","安提瓜和巴布达"),
    AI("AI","Anguilla","安圭拉"),
    AL("AL","Albania","阿尔巴尼亚"),
    AM("AM","Armenia","亚美尼亚"),
    AO("AO","Angola","安哥拉"),
    AQ("AQ","Antarctica","南极洲"),
    AR("AR","Argentina","阿根廷"),
    AS("AS","American Samoa","美属萨摩亚"),
    AT("AT","Austria","奥地利"),
    AU("AU","Australia","澳大利亚"),
    AW("AW","Aruba","阿鲁巴"),
    AX("AX","aland Island","奥兰群岛"),
    AZ("AZ","Azerbaijan","阿塞拜疆"),
    BA("BA","Bosnia & Herzegovina","波黑"),
    BB("BB","巴巴多斯","巴巴多斯"),
    BD("BD","Bangladesh","孟加拉"),
    BE("BE","Belgium","比利时"),
    BF("BF","Burkina","布基纳法索"),
    BG("BG","Bulgaria","保加利亚"),
    BH("BH","Bahrain","巴林"),
    BI("BI","Burundi","布隆迪"),
    BJ("BJ","Benin","贝宁"),
    BL("BL","Saint Barthélemy","圣巴泰勒米岛"),
    BM("BM","Bermuda","百慕大"),
    BN("BN","Brunei","文莱"),
    BO("BO","Bolivia","玻利维亚"),
    BQ("BQ","Caribbean Netherlands","荷兰加勒比区"),
    BR("BR","Brazil","巴西"),
    BS("BS","The Bahamas","巴哈马"),
    BT("BT","Bhutan","不丹"),
    BV("BV","Bouvet Island","布韦岛"),
    BW("BW","Botswana","博茨瓦纳"),
    BY("BY","Belarus","白俄罗斯"),
    BZ("BZ","Belize","伯利兹"),
    CA("CA","Canada","加拿大"),
    CC("CC","Cocos (Keeling) Islands","科科斯群岛"),
    CF("CF","Central African Republic","中非"),
    CH("CH","Switzerland","瑞士"),
    CL("CL","Chile","智利"),
    CM("CM","Cameroon","喀麦隆"),
    CO("CO","Colombia","哥伦比亚"),
    CR("CR","Costa Rica","哥斯达黎加"),
    CU("CU","Cuba","古巴"),
    CV("CV","Cape Verde","佛得角"),
    CX("CX","Christmas Island","圣诞岛"),
    CY("CY","Cyprus","塞浦路斯"),
    CZ("CZ","Czech Republic","捷克"),
    DE("DE","Germany","德国"),
    DJ("DJ","Djibouti","吉布提"),
    DK("DK","Denmark","丹麦"),
    DM("DM","Dominica","多米尼克"),
    DO("DO","Dominican Republic","多米尼加"),
    DZ("DZ","Algeria","阿尔及利亚"),
    EC("EC","Ecuador","厄瓜多尔"),
    EE("EE","Estonia","爱沙尼亚"),
    EG("EG","Egypt","埃及"),
    EH("EH","Western Sahara","西撒哈拉"),
    ER("ER","Eritrea","厄立特里亚"),
    ES("ES","Spain","西班牙"),
    FI("FI","Finland","芬兰"),
    FJ("FJ","Fiji","斐济群岛"),
    FK("FK","Falkland Islands","马尔维纳斯群岛（ 福克兰）"),
    FM("FM","Federated States of Micronesia","密克罗尼西亚联邦"),
    FO("FO","Faroe Islands","法罗群岛"),
    FR("FR","France","法国"),
    GA("GA","Gabon","加蓬"),
    GD("GD","Grenada","格林纳达"),
    GE("GE","Georgia","格鲁吉亚"),
    GF("GF","French Guiana","法属圭亚那"),
    GH("GH","Ghana","加纳"),
    GI("GI","Gibraltar","直布罗陀"),
    GL("GL","Greenland","格陵兰"),
    GN("GN","Guinea","几内亚"),
    GP("GP","Guadeloupe","瓜德罗普"),
    GQ("GQ","Equatorial Guinea","赤道几内亚"),
    GR("GR","Greece","希腊"),
    GS("GS","South Georgia and the South Sandwich Islands","南乔治亚岛和南桑威奇群岛"),
    GT("GT","Guatemala","危地马拉"),
    GU("GU","Guam","关岛"),
    GW("GW","Guinea-Bissau","几内亚比绍"),
    GY("GY","Guyana","圭亚那"),
    HK("HK","Hong Kong","香港"),
    HM	("HM","Heard Island and McDonald Islands","赫德岛和麦克唐纳群岛"),
    HN("HN","Honduras","洪都拉斯"),
    HR("HR","Croatia","克罗地亚"),
    HT("HT","Haiti","海地"),
    HU("HU","Hungary","匈牙利"),
    ID("ID","Indonesia","印尼"),
    IE("IE","Ireland","爱尔兰"),
    IL("IL","Israel","以色列"),
    IM("IM","Isle of Man","马恩岛"),
    IN("IN","India","印度"),
    IO("IO","British Indian Ocean Territory","英属印度洋领地"),
    IQ("IQ","Iraq","伊拉克"),
    IR("IR","Iran","伊朗"),
    IS("IS","Iceland","冰岛"),
    IT("IT","Italy","意大利"),
    JE("JE","Jersey","泽西岛"),
    JM("JM","Jamaica","牙买加"),
    JO("JO","Jordan","约旦"),
    JP("JP","Japan","日本"),
    KH("KH","Cambodia","柬埔寨"),
    KI("KI","Kiribati","基里巴斯"),
    KM("KM","The Comoros","科摩罗"),
    KW("KW","Kuwait","科威特"),
    KY("KY","Cayman Islands","开曼群岛"),
    LB("LB","Lebanon","黎巴嫩"),
    LI("LI","Liechtenstein","列支敦士登"),
    LK("LK","Sri Lanka","斯里兰卡"),
    LR("LR","Liberia","利比里亚"),
    LS("LS","Lesotho","莱索托"),
    LT("LT","Lithuania","立陶宛"),
    LU("LU","Luxembourg","卢森堡"),
    LV("LV","Latvia","拉脱维亚"),
    LY("LY","Libya","利比亚"),
    MA("MA","Morocco","摩洛哥"),
    MC("MC","Monaco","摩纳哥"),
    MD("MD","Moldova","摩尔多瓦"),
    ME("ME","Montenegro","黑山"),
    MF("MF","Saint Martin (France)","法属圣马丁"),
    MG("MG","Madagascar","马达加斯加"),
    MH("MH","Marshall islands","马绍尔群岛"),
    MK("MK","Republic of Macedonia (FYROM)","马其顿"),
    ML("ML","Mali","马里"),
    MM("MM","Myanmar (Burma)","缅甸"),
    MO("MO","Macao","澳门"),
    MQ("MQ","Martinique","马提尼克"),
    MR("MR","Mauritania","毛里塔尼亚"),
    MS("MS","Montserrat","蒙塞拉特岛"),
    MT("MT","Malta","马耳他"),
    MV("MV","Maldives","马尔代夫"),
    MW("MW","Malawi","马拉维"),
    MX("MX","Mexico","墨西哥"),
    MY("MY","Malaysia","马来西亚"),
    NA("NA","Namibia","纳米比亚"),
    NE("NE","Niger","尼日尔"),
    NF("NF","Norfolk Island","诺福克岛"),
    NG("NG","Nigeria","尼日利亚"),
    NI("NI","Nicaragua","尼加拉瓜"),
    NL("NL","Netherlands","荷兰"),
    NO("NO","Norway","挪威"),
    NP("NP","Nepal","尼泊尔"),
    NR("NR","Nauru","瑙鲁"),
    OM("OM","Oman","阿曼"),
    PA("PA","Panama","巴拿马"),
    PE("PE","Peru","秘鲁"),
    PF("PF","French polynesia","法属波利尼西亚"),
    PG("PG","Papua New Guinea","巴布亚新几内亚"),
    PH("PH","The Philippines","菲律宾"),
    PK("PK","Pakistan","巴基斯坦"),
    PL("PL","Poland","波兰"),
    PN("PN","Pitcairn Islands","皮特凯恩群岛"),
    PR("PR","Puerto Rico","波多黎各"),
    PS("PS","Palestinian territories","巴勒斯坦"),
    PW("PW","Palau","帕劳"),
    PY("PY","Paraguay","巴拉圭"),
    QA("QA","Qatar","卡塔尔"),
    RE("RE","Réunion","留尼汪"),
    RO("RO","Romania","罗马尼亚"),
    RS("RS","Serbia","塞尔维亚"),
    RU("RU","Russian Federation","俄罗斯"),
    RW("RW","Rwanda","卢旺达"),
    SB("SB","Solomon Islands","所罗门群岛"),
    SC("SC","Seychelles","塞舌尔"),
    SD("SD","Sudan","苏丹"),
    SE("SE","Sweden","瑞典"),
    SG("SG","Singapore","新加坡"),
    SI("SI","Slovenia","斯洛文尼亚"),
    SJ("SJ","Template:Country data SJM Svalbard","斯瓦尔巴群岛和 扬马延岛"),
    SK("SK","Slovakia","斯洛伐克"),
    SL("SL","Sierra Leone","塞拉利昂"),
    SM("SM","San Marino","圣马力诺"),
    SN("SN","Senegal","塞内加尔"),
    SO("SO","Somalia","索马里"),
    SR("SR","Suriname","苏里南"),
    SS("SS","South Sudan","南苏丹"),
    ST("ST","Sao Tome & Principe","圣多美和普林西比"),
    SV("SV","El Salvador","萨尔瓦多"),
    SY("SY","Syria","叙利亚"),
    SZ("SZ","Swaziland","斯威士兰"),
    TC("TC","Turks & Caicos Islands","特克斯和凯科斯群岛"),
    TD("TD","Chad","乍得"),
    TG("TG","Togo","多哥"),
    TH("TH","Thailand","泰国"),
    TK("TK","Tokelau","托克劳"),
    TL("TL","Timor-Leste (East Timor)","东帝汶"),
    TN("TN","Tunisia","突尼斯"),
    TO("TO","Tonga","汤加"),
    TR("TR","Turkey","土耳其"),
    TV("TV","Tuvalu","图瓦卢"),
    TZ("TZ","Tanzania","坦桑尼亚"),
    UA("UA","Ukraine","乌克兰"),
    UG("UG","Uganda","乌干达"),
    US("US","United States of America (USA)","美国"),
    UY("UY","Uruguay","乌拉圭"),
    VA("VA","Vatican City (The Holy See)","梵蒂冈"),
    VE("VE","Venezuela","委内瑞拉"),
    VG("VG","British Virgin Islands","英属维尔京群岛"),
    VI("VI","United States Virgin Islands","美属维尔京群岛"),
    VN("VN","Vietnam","越南"),
    WF("WF","Wallis and Futuna","瓦利斯和富图纳"),
    WS("WS","Samoa","萨摩亚"),
    YE("YE","Yemen","也门"),
    YT("YT","Mayotte","马约特"),
    ZA("ZA","South Africa","南非"),
    ZM("ZM","Zambia","赞比亚"),
    ZW("ZW","Zimbabwe","津巴布韦"),
    CN("CN","China","中国 内地"),
    CG("CG","Republic of the Congo","刚果（布）"),
    CD("CD","Democratic Republic of the Congo","刚果（金）"),
    MZ("MZ","Mozambique","莫桑比克"),
    GG("GG","Guernsey","根西岛"),
    GM("GM","Gambia","冈比亚"),
    MP("MP","Northern Mariana Islands","北马里亚纳群岛"),
    ET("ET","Ethiopia","埃塞俄比亚"),
    NC("NC","New Caledonia","新喀里多尼亚"),
    VU("VU","Vanuatu","瓦努阿图"),
    TF("TF","French Southern Territories","法属南部领地"),
    NU("NU","Niue","纽埃"),
    UM("UM","United States Minor Outlying Islands","美国本土外小岛屿"),
    CK("CK","Cook Islands","库克群岛"),
    GB("GB","Great Britain (United Kingdom; England)","英国"),
    TT("TT","Trinidad & Tobago","特立尼达和多巴哥"),
    VC("VC","St. Vincent & the Grenadines","圣文森特和格林纳丁斯"),
    TW("TW","Taiwan","中华民国（台湾）"),
    NZ("NZ","New Zealand","新西兰"),
    SA("SA","Saudi Arabia","沙特阿拉伯"),
    LA("LA","Laos","老挝"),
    KP("KP","North Korea","朝鲜 北朝鲜"),
    KR("KR","South Korea","韩国 南朝鲜"),
    PT("PT","Portugal","葡萄牙"),
    KG("KG","Kyrgyzstan","吉尔吉斯斯坦"),
    KZ("KZ","Kazakhstan","哈萨克斯坦"),
    TJ("TJ","Tajikistan","塔吉克斯坦"),
    TM("TM","Turkmenistan","土库曼斯坦"),
    UZ("UZ","Uzbekistan","乌兹别克斯坦"),
    KN("KN","St. Kitts & Nevis","圣基茨和尼维斯"),
    PM("PM","Saint-Pierre and Miquelon","圣皮埃尔和密克隆"),
    SH("SH","St. Helena & Dependencies","圣赫勒拿"),
    LC("LC","St. Lucia","圣卢西亚"),
    MU("MU","Mauritius","毛里求斯"),
    CI("CI","C?te d'Ivoire","科特迪瓦"),
    KE("KE","Kenya","肯尼亚"),
    MN("MN","Mongolia","蒙古国 蒙古");



    private String nameDB;
    private String nameEN;
    private String nameCN;

    EnumCountry(String nameDB, String nameBigNet, String nameCN) {
        this.nameDB = nameDB;
        this.nameEN = nameBigNet;
        this.nameCN = nameCN;
    }

    public String getNameDB(){
        return nameDB;
    }
    public String getNameEN(){
        return nameEN;
    }

    public static String getNameBigNetByDB(String nameDB) {
        EnumCountry[] values = EnumCountry.values();
        for (EnumCountry value : values) {
            if (Objects.equals(value.nameDB, nameDB)){
                return value.nameEN;
            }
        }
        return nameDB;
    }

    public static String getNameDBByBigNet(String nameBigNet) {
        EnumCountry[] values = EnumCountry.values();
        for (EnumCountry value : values) {
            if (Objects.equals(value.nameEN, nameBigNet)){
                return value.nameDB;
            }
        }
        return nameBigNet;
    }

}
